### ISSUE TITLE
x_train.shape

### ISSUE THREAD

**Issue by DrBanana00** [SibPrasad/Detection-and-Prevention-of-Banana-Leaf-Disease#3]
I couldn't get the same output. Is there any missing code that could have miss out?
x_train.shape
(1766, 200, 200, 3)
![image](https://user-images.githubusercontent.com/85335787/124434968-149c5a00-dda7-11eb-85b4-03bf86e68ba4.png)

My error ↓
x_train.shape
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-94-2132a220a582> in <module>
----> 1 x_train.shape
AttributeError: 'list' object has no attribute 'shape'
![image](https://user-images.githubusercontent.com/85335787/124434520-8cb65000-dda6-11eb-9d27-8f827846eaaa.png)

**Comment by SibaPrasad2221** [comment]
List object has no attribute shape, that means you can not use shape function in a list, so convert x_train list to numpy array.
Hope that will work.

Hint: x=np.array(x)
then x.shape
